### ISSUE TITLE
"Home" bug

### ISSUE THREAD

**Issue by pepijn809** [senpaiski/TopAnimeStream#17]
After loggin in, the home tab is displayed. It looks good, but once you press on one of the "latest" animes. You are automaticly logged out.

Once you login, you end up at "home" again. Meaning this represents a loop.

**Comment by senpaiski** [comment]
I've look into this and you don't log out but instead you are redirected to the the login screen because it's the default page when the app is unable to find the link (404 not found). The onclick function in the home page for the latest episode list is not implemented so I just need to add a link that will start playing the episode automatically.

In other words, it's not implemented yet and It will be fix in the next version.
Thanks!

**Comment by pepijn809** [comment]
Great! 

ty
