### ISSUE TITLE
"Logged out"

### ISSUE THREAD

**Issue by pepijn809** [senpaiski/TopAnimeStream#18]
After certain (still untested) clicks i automaticly get logged out of the client. This also seems to happen over time, not sure why exactly.

Just a note, i will be testing more, perhaps to look for patterns.

**Comment by senpaiski** [comment]
Can't seem to reproduce this, but by design after a couple of hours of inactivity when clicking on something, you will be ask to login again.

Maybe, it's the same issue of #17 
If you still see the top header bar with your name on the right this is means you are not logout but simply on the login screen. You could just click on home again without submitting your login information.

**Comment by pepijn809** [comment]
I hope it is, if it happens again. I will report it asap ;)

ty
