### ISSUE TITLE
Secure / not secure? Wrong url's provided?

### ISSUE THREAD

**Issue by mnemanja** [senpaiski/TopAnimeStream#29]
The links for register and download on Readme page lead to to https domain, which it clearly isn't. What's up with that?

**Comment by senpaiski** [comment]
Use http://www.topanimestream.com/ if you don't want to use https. I have a new hosting provider and I can't add my ssl certificate for free thats why you see a red color warning message when using https.

**Comment by mnemanja** [comment]
@senpaiski Cool, no problem.
By the way, what's with the desktop app? Is there a way to download it at this moment, or at some later point?

**Comment by senpaiski** [comment]
It's deprecated and I don't plan on making it work again unless I have a bunch of people who wants it back. It was not popular enough.

**Comment by mnemanja** [comment]
@senpaiski  I'd definitely like to try it.
How can I add my voice to the list of other peoples requests for the desktop app? Any way you could provide me with the app itself just to see how it works, and use it if possible?

Cheers and keep up with the good work.

**Comment by senpaiski** [comment]
The latest code is from this branch https://github.com/senpaiski/TopAnimeStream/tree/dev and I haven't updated it for more than a year. It will not work out of the box and you will need to make a lot of tweaks here and there. Maybe I can create a version with the basic video functions working. Nothing fancy but just so that it works. Right now, I don't have the time to do that because I'm working on other projects + TopAnimeStream is not top priority anymore. In the meantime, you can fork and try to fix it.
