### ISSUE TITLE
What happened to TopAnimeStream?

### ISSUE THREAD

**Issue by Draxler** [senpaiski/TopAnimeStream#30]
Will this project still be maintained in the future or is it dead?, since redirects users from TopAnimeStream
website onto some third party video website when try to enter TopAnimeStream website ..
Regards

**Comment by pepijn809** [comment]
@Draxler 
It's a small world, isn't it? :) 

TopAnimeStream took a lot of time to keep up to date, and there was simply not enough interest from it's userbase to keep it alive. The developers who were involved moved on with different interests, which is why TopAnimeStream shutdown and/or is now defunct. It remains to be seen, whether or it will stay defunct forever. However anybody is able find the source code on this Github Repository, and therefor anyone could potentially bring it back to 'life'. '@senpaiski' created a new application/website called 'vHub' to suit his and others needs for specific video content delivery. 

TAS has since been replaced by 'vHub', which i assume is the creators vision of a broughter homebase for specific video content delivery.

**Comment by Draxler** [comment]
Hi Pepijn809 , small world indeed :) 

Thanks a lot for letting me know what happend here. It's a shame TopAnimeStream is gone since a lot of work and time went into it. Maybe @senpaiski should keep anime desktop app (which i liked very much btw) since it was 1 of kind , the only anime desktop app. Maybe this way TopAnimeStream userbase would be stronger/bigger (but i could be wrong never the less..)  :) Wish @senpaiski much luck in next project.
Regards
